todo_project/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('create/', views.todo_create, name='todo_create'),
    path('update/<int:pk>/', views.todo_update, name='todo_update'),
    path('delete/<int:pk>/', views.todo_delete, name='todo_delete'),
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo_project/todo/models.py
from django.db import models

class TodoItem(models.Model):
    title = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todo_project/todo/forms.py
from django import forms
from .models import TodoItem

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['title', 'completed']

todo_project/todo/views.py
from django.shortcuts import render, redirect
from .models import TodoItem
from .forms import TodoForm

def todo_list(request):
    todos = TodoItem.objects.all()
    return render(request, 'todo/todo_list.html', {'todos': todos})

def todo_create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo:todo_list')
    else:
        form = TodoForm()
    return render(request, 'todo/todo_form.html', {'form': form})

def todo_update(request, pk):
    todo = TodoItem.objects.get(pk=pk)
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('todo:todo_list')
    else:
        form = TodoForm(instance=todo)
    return render(request, 'todo/todo_form.html', {'form': form})

def todo_delete(request, pk):
    todo = TodoItem.objects.get(pk=pk)
    todo.delete()
    return redirect('todo:todo_list')

todo_project/todo/templates/todo/todo_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Todo Form</title>
</head>
<body>
    <h2>Todo Form</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

todo_project/todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Todo List</title>
</head>
<body>
    <h2>Todo List</h2>
    <ul>
        {% for todo in todos %}
            <li>
                {{ todo.title }}
                <a href="{% url 'todo:todo_update' pk=todo.id %}">Edit</a>
                <a href="{% url 'todo:todo_delete' pk=todo.id %}">Delete</a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'todo:todo_create' %}">Add Todo</a>
</body>
</html>